# fly.toml app configuration file generated for songinsight-frontend on 2025-07-15T17:21:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'songinsight-frontend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '1s'
  interval = '15s'
  method = 'get'
  path = '/'
  protocol = 'http'
  timeout = '2s'
  tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
